### ISSUE TITLE
Switch from nosetests to pytest

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nistats#211]
Should be simple, pytest can run most aspects of nosetests. I did a pilot in https://github.com/neurospin/pypreprocess and it worked fine (undid it due to other reasons). We replace the command nosetests with pytest and that's pretty much it.
ALso see https://github.com/nilearn/nilearn/issues/1752

**Comment by bthirion** [comment]
Please proceed. Thx.

**Comment by bthirion** [comment]
I'm not sure why new functions are needed, but I agree with the general idea of switching for travis.

**Comment by kchawla-pi** [comment]
I write everything in functions.
An example is in the code I wrote for #228 .
Most of them won't be user facing. I need to have tests for them. Currently all the tests are part of integration tests. There are no unit tests at all. I will write unit tests (and integration tests)
