### ISSUE TITLE
first_level_models_from_bids uses wrong conventions

### ISSUE THREAD

**Issue by bthirion** [nilearn/nistats#225]
It does not enforce current BIDS conventions (e.g. fMRI images prepended with 'preproc'), and returns events as a list, which is a poor choice.

**Comment by satra** [comment]
@bthirion  - the `preproc` keyword was dropped in the derivatives meeting.hopefully rc1 at the end of the month will clarify a bunch of things.

also is there a reason why pybids is not being used for bids model transformations? that will help with conventions as well.

**Comment by bthirion** [comment]
Historically, I think that this was done in parallel. We need to look more directly into pybids. Hopefully this can clarify our code for handling BIDS conventions.
