### ISSUE TITLE
Nistats has no continuous testing support for Windows platform

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nistats#235]
We should add Appveyor for Nistats, the way we have for Nilearn.
Nistats is planned to be merged with Nilearn & Nistats test must work on AppveyorCI before the merge.
If not, Nilearn AppveyorCI may start failing post merge & might be more complex to fix than in a small separate library such as Nistats.

**Comment by bthirion** [comment]
Good point -- though not an emergency. B

**Comment by kchawla-pi** [comment]
Most of the green sections do not. need to be reviewed, they are full of unmodified code which has been slightly restructured but is showing up as new additions in the Github diff.

I will describe what I did & why, and clarify the parts that actually need to be reviewed.
