### ISSUE TITLE
 Better installation using pip requirements file

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nistats#240]
Also for Nilearn: https://github.com/nilearn/nilearn/issues/1770

Currently all the necessary dependencies for Nistats need to be manually installed, by following the documentation. We can streamline the experience for new users by employing a requirements file.

SO instead of having to manually install scipy, then scikit-learn then nilearn, then matplotlib etc, and then installing nistats, a user only has to do pip install nistats and be done.

**Comment by bthirion** [comment]
I believe that this shuld be fixed in Nilearn first.
