### ISSUE TITLE
No new Pull Requests

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nistats#398]
I am starting the work to incorporate `nistats` into `nilearn`. Once the current crop of PRs have been merged, we should not accept any new PRs here.

Instead, I would like to focus my energy on adding nistats into nilearn quickly so we can make improvements there.

**Comment by jeromedockes** [comment]
there may still be a few things to do in nistats, e.g.
- remove dependencies that won't be added to nilearn
- change tests that create files in the source directory and don't
  remove them

**Comment by kchawla-pi** [comment]
I will incorporate those changes into the nilearn.stats PR.
Most of the changes such as  tweaking tests for better cleanup, I will do in the nilearn.stats PR.

**Comment by jeromedockes** [comment]
I think there are many things for you to do alone in your nilearn PR
also looking at some coverage report e.g. https://codecov.io/gh/nistats/nistats/pull/414/tree/nistats I see that important parts of the core modules such as first_level_model (83%), second_level_model (83%), or regression (77%) are not covered, maybe we should tick these off in several small PRs on the nistats repo

**Comment by kchawla-pi** [comment]
I am think abut the best way to do that.7By not opening new PRs, I mean not opening new PRs that don't specifically serve the purpose of `nilearn.stats` or may drag on for a month or two, as happens often enough with most PRs.

Thinking of best way to do it. Seems to me a better way would be to open a branch in Nilearn (not a PR) and keep adding modifications to this branch until the feature is ready for a merge.

Regarding test coverage, Nilearn and Nistats are both overall at 92% so I don't consider it a blocker. Specific files may have less coverage and that can be addressed as a regular nilearn PR, post Nistats merge.

There are lots of fixes and tweaks to be done in Nistats. They require more internal & external developer participation which will be improved by nilearn.stats . Indeed that's the primary reason we're doing the merge.

Waiting around for most issues to be addressed within the Nistats repo first will significantly delay the entire endeavoor.
